### ISSUE TITLE
stun animation doesn't play in level 1-2

### ISSUE THREAD

**Issue by dannyblackstock** [JoanIat312/410#23]

**Comment by JoanIat312** [comment]
i've been debugging this for a while, I notice that when i do 

> Debug.Log( (Time.time > gameManager.stunUseDelayTimeStamp) + ", " + Input.GetKeyDown (KeyCode.Space));

on all other level, it returns true and ture, but when i do it in level 1-2, it either returns true and false, or false and true. They can never be true at the sametime, which is why the animation is not playing. Havent figure out what happened.

**Comment by dannyblackstock** [comment]
fixed in b2e97a2440df416cb7c0e993e2b2dabaaff663c0
